### ISSUE TITLE
[QUESTION] Persistent simulation: How to end a session?

### ISSUE THREAD

**Issue by vinerz** [EnsoFinance/transaction-simulator#11]
Hey there! First of all, thank you for such a blazing fast implementation of a transaction simulator. I am still stunned about how performant it is.

As a disclaimer, my knowledge about Rust memory allocation is far from the best.

I am using a multi-step simulation getting a session ID and I wasn't able to find an endpoint to close such a session, so in my understanding, this session will be kept in memory during the entire runtime unless the server is restarted, right? As I am hammering the service with thousands of different concurrent sessions that won't be reused, I got a bit worried about them lingering for eternity.

Am I correct in this assumption?

Cheers!

**Comment by ape-dev-cs** [comment]
Yeah, this is a messup in my implementation. I'll open a PR soon to add one.

**Comment by ape-dev-cs** [comment]
Addressed here: https://github.com/EnsoFinance/transaction-simulator/pull/12
