### ISSUE TITLE
Formattrace - Huge impact on performance

### ISSUE THREAD

**Issue by polyphia** [EnsoFinance/transaction-simulator#13]
I'm not sure if this is expected behavior, but when benchmarking around 100 simulations of single txs I get the following results :

Without formattrace : 200 / 300 ms

With formattrace : 1.5-2.5 seconds

Is this normal ?

Also not sure why in the env file it says formattrace won't work without etherscan API key, I get the same formattrace format regardless if I use key or not .

**Comment by devanoneth** [comment]
It is definitely expected, formatting the trace requires quite a lot of extra computation and network requests. If you need speed, I'd recommend not formatting them.

Regarding the message in the `.env.example`, it's not exactly correct. What it should say is that the formatted traces will have more contract and function names if you include the Etherscan API key. Have you noticed this?
