### ISSUE TITLE
Support for Shanghai / Solidity 0.8.20

### ISSUE THREAD

**Issue by ape-dev-cs** [EnsoFinance/transaction-simulator#6]
Tangentially related to other issues, but as an old version of revm is used, the PUSH0 opcode introduced in Shanghai will always cause a revert, meaning that anything compiled with 0.8.20 won't run in the simulator.

**Comment by polyphia** [comment]
Indeed, now it makes sense why all my contract transactions got reverted without any apparent reason !

Tried with an older contract deployment using 0.8.0 and worked well
